global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "inference_api"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "exporter_metrics"
    static_configs:
      - targets: ["localhost:9000"]
